### ISSUE TITLE
`Struct.parse` isn't exhaustively typed

### ISSUE THREAD

**Issue by demberto** [timrid/construct-typing#24]
```py
def parse(data: bytes, **contextkw: ContextKWType) -> Container[Any]
```

This is the type hint you have used for it. However the docstring of this function mentions it can support a whole lot of other types (from bytes, bytearray, memoryview, array etc.). The closest type hint which comes to my mind is `_typeshed.ReadableBuffer` for this.

**Comment by timrid** [comment]
I used only `bytes` because until Python 3.10 the documentation says

```
typing.ByteString

This type represents the types bytes, bytearray, and memoryview of byte sequences.

As a shorthand for this type, bytes can be used to annotate arguments of any of the types mentioned above.
```
(see [here](https://docs.python.org/3.10/library/typing.html#typing.ByteString)) 

But with [PEP688](https://peps.python.org/pep-0688/#no-special-meaning-for-bytes) this will be removed. So I will change it in the future with a better type.
